# MERT optimized configuration
# decoder /opt/pbsmt/tools/mosesdecoder/bin/moses
# BLEU 0.112289 on dev /workspace/data/work/valid.tc.en
# We were before running iteration 3
# finished Tue Mar 31 16:35:21 UTC 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=reordering-table.wbe-msd-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=lm.binary order=5

# dense weights for feature functions

[threads]
4

[v]
0
[weight]

LexicalReordering0= 0.048294 0.0218654 0.082628 0.0851926 0.032476 0.0542117
Distortion0= 0.0510442
LM0= 0.0652665
WordPenalty0= -0.20586
PhrasePenalty0= 0.199173
TranslationModel0= 0.0117144 0.0531399 0.0624609 0.0266731
UnknownWordPenalty0= 1
