# MERT optimized configuration
# decoder /opt/pbsmt/tools/mosesdecoder/bin/moses
# BLEU 0.155993 on dev /workspace/data/work/valid.tc.de
# We were before running iteration 3
# finished Tue Mar 31 16:40:00 UTC 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=reordering-table.wbe-msd-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=lm.binary order=5

# dense weights for feature functions

[threads]
4

[v]
0
[weight]

LexicalReordering0= 0.0655449 0.0330636 0.0276407 0.0438525 0.0378039 0.0649147
Distortion0= 0.0493152
LM0= 0.105705
WordPenalty0= -0.288137
PhrasePenalty0= 0.0313858
TranslationModel0= 0.0283338 0.098831 0.0684114 0.05706
UnknownWordPenalty0= 1
